black-sliver/PopTracker

.gitmodules
macosx/bundle_macosx_app.sh
src/core/fileutil.h

Added compatibility for MacOSX
- Alternate getAppPath function in fileutil.h to make sure assets can be retrieved relatively to the executable.
- Added a script to create an app bundle from the executable.
- Added submodule dependency on prebuilt SDL libraries for MacOSX. This is necessary as we can't use install-name-tool on the libraries compiled with brew. Feel free to remove that dependency if you can find an alternative.
Example usage for `bundle_macosx_app.sh`:
`./macosx/bundle_macosx_app.sh build/darwin-x86_64/poptracker --version=0.2 --bundle-name=PopTracker`
This will create a `PopTracker.app` bundle next the the executable in `build/darwin-x86_64` with version set to `0.2` and bundle name set to `PopTracker`

MacOSX compatibility

---

src/uilib/ui.cpp

Since this app isn't frame-sensitive or a game, there's no need to disable
compositing. This will also avoid causing issues in KWin environments, for
example Firefox rendering hangs.

Don't disable compositing in X11.

---

Makefile
macosx/build_thirdparty.sh
macosx/bundle_macosx_app.sh

- Added script `build_thirdparty.sh` to clone and build third party libraries to be compatible with PopTracker bundle.
- Updated `bundle_macosx_app.sh` to adjust paths for new libraries.

Updated Mac OS bundle

---

PLUGIN LICENSE ADDENDUM.md
README.md

This adds a definition on how we want to handle licenses for plug-ins. Specifically the suggestion to support NDI is affected by this, because the NDI dll/sdk itself is not free software.  Since this might be a license exception, contributors to code of what is released together with this definition will have to approve to merge this.
Technically, C++ source code was only touched by myself and @pkprotoplasm as far as I can see.
However I would have a better feeling if @sbzappa, @Cyb3RGER, @ScipioWright and @lurch9229 could approve as well.
Since this will affect #52, approval by @coavins would also be appreciated.
Please comment and let me know if you have concerns, want to add something or outright want to block this. Otherwise please hit approve on the right.

Add plug-in license clarification

---

schema/packs/strict/manifest.json

Fixes minor typo in manifest strict schema "mainfest" -> "manifest".

fix manifest strict schema typo "mainfest"

---

community-packs.json

Decided to move it to its own branch to stop muddying up my commit history 🤷

Change versions url for The Messenger Track Pack

---

schema/packs/locations.json
schema/packs/strict/locations.json

Match wording of description for access rules in json schema with docs to accurately reflect usage

Fix description for optional access rules in json schema

---

src/ap/aptracker.h

* use bundled cert store for archipelago ssl connections (fixes issues on macos and outdated windows)
* update apclientpp for per-game-ids

AP: apclient autotracking update

---

src/core/scripthost.cpp

* don't use possibly-stale reference
we use [] on vector because the callback list can change during execution,
the .dirty=false would then use a stale reference, writing a 0 to random memory
* clean up remains of old code

Fix memory watch crash

---

doc/PACKS.md
src/core/tracker.cpp

Abort execution of Lua user function (`$`-Rule) after 100k instructions to avoid hanging on recursion and endless-loops.
This allows having recursion in logic that automatically aborts as unreachable - for performance reasons it would be better to detect or avoid such recursion in user code where possible.
Adds a global `DEBUG` to control how noisy error reporting is.

Lua timeout hook

---

Makefile
src/luasandbox/require.h
src/poptracker.cpp

this uses c++ exceptions to unwind the stack to avoid memory leaks when throwing lua errors

Build Lua with c++

---

src/core/fileutil.h
src/core/statemanager.cpp
src/main.cpp
src/poptracker.cpp

Addresses https://discord.com/channels/937157230963339364/937163355339235369/1191426494547894272

Encode to/from utf8 when storing/loading path from json

---

src/core/tracker.cpp

While 100k was plenty, it's easy to write code that accidentally goes over it. 500k should be safe to where the program does not hang indefinitely on most PCs.

Lua rules: increase execution limit to 500k

---

doc/PACKS.md
schema/packs/locations.json
schema/packs/strict/locations.json
src/core/location.cpp
src/core/tracker.cpp

* `^$func ` will call global Lua function `func` for AccessibilityLevel rather than bool/count. Possible return values are
* `AccessibilityLevel.None`, replaces `false` (Red)
* `AccessibilityLevel.Normal`, replaces `true` (Green)
* `AccessibilityLevel.SequenceBreak`, replaces `[]` syntax (Yellow)
* `AccessibilityLevel.Inspect`, replaces `{}` syntax (Blue)
* parents are still evaluated so that e.g. `SequenceBreak + Normal = SequenceBreak`
* allow defining access rule as single string, which is equivalent to `[[string]]`, i.e. a single code or func.

Extend rule syntax

---

doc/PACKS.md
src/core/scripthost.cpp
src/luasandbox/require.h

* set `...` for ScriptHost:LoadScript
* set `...` for require
* properly resolve mod name -> path for require

Lua: properly implement require from pack

---

.github/workflows/test.yaml
Makefile
api/README.md
api/lua/definition/poptracker.lua
doc/AUTOTRACKING.md
doc/PACKS.md
examples/ap-storage-example/.luarc.json
examples/ap-storage-example/scripts/autotracking.lua
examples/hosted_item/.luarc.json
examples/hosted_item/locations/locations.jsonc
examples/hosted_item/scripts/init.lua
examples/hosted_item/scripts/logic.lua
examples/luminosity-test/.luarc.json
examples/margin-test/.luarc.json
examples/uat-example/.luarc.json
examples/uat-example/scripts/autotracking.lua
examples/uat-example/scripts/init.lua

This adds a LuaLS definition file to PopTracker to get proper auto-complete suggestions, warnings and type hints for Lua files.
LuaLS has a builtin linter and a builtin typing system. The example packs (all but the template pack) were updated to get rid of all linter warnings.
To test the Definition File, create an `api/lua/definition` folder next to your `PopTracker.exe` and put the [PopTracker.lua](https://github.com/black-sliver/PopTracker/blob/lua-ls/api/lua/definition/poptracker.lua) there. Put the [.luarc.json](https://github.com/black-sliver/PopTracker/blob/lua-ls/examples/uat-example/.luarc.json) into your pack. The example path is `../../api/lua/definition`, so this should work if your pack is in `<exe_dir>\packs\...` after creating said folder and file. And then install LuaLS …

Add LuaLS definition file and update example and docs

---

src/core/tracker.cpp

Forgot to pop the comparison args from stack when `DEBUG = true`, resulting in `nil` error message for "Limit reached" errors.

Lua: fix error handler messsage when DEBUG = true

---

api/lua/definition/poptracker.lua
doc/PACKS.md
src/core/scripthost.cpp
src/core/scripthost.h
src/core/tracker.cpp
src/core/tracker.h
src/poptracker.cpp

Adds `ScriptHost:AddOnFrameHandler` and `ScriptHost:RemoveOnFrameHandler` to run Lua code every frame.
Also minor cleanup in ScriptHost to avoid duplicate code when calling Lua functions and added Execution Limit for Memory Watches as a side-effect.

Lua: add OnFrame event

---

src/ui/mapwidget.cpp

instead of mixed colors. For installations that never toggled the setting before.

Map: default to split color locations

---

.github/workflows/binaries.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml

* Release build targets older macos.
* Test build currently fails to find headers sdl2-config --cflags on -latest

CI: use macos-13

---

doc/AUTOTRACKING.md

File we linked to was renamed to fix a typo, we now have to fix it as well.

Doc: qusb fixed the typo in the filename

---

.github/workflows/test.yaml
Makefile

* Fix build on M1 (need explicit -I and -L for brew)
* Convert CI to use a matrix running on both macos-13/amd64 and macos-latest/arm64/m1
* Increase parallel compilation to what the runners now provide

CI: embrace the M1

---

doc/PACKS.md
src/core/jsonitem.cpp

Ignore `"allow_disabled"` for toggle, static and toggle_badged. It was never documented that it does something.
Also make internal handling of `allowDisabled` more consistent.

JsonItem: ignore allow_disabled for Toggle, Static and Toggle Badged

---

.github/workflows/binaries.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml

Hopefully we catch the problem if a later step fails, but link ~~warning~~ error returning non-zero stops us from running tests. Brew reports errors and warnings in a way that is compatible to GH messages, so the error is visible in the run overview.

CI: ignore brew non-zero exit code

---

api/lua/definition/poptracker.lua
src/ap/aptracker.h
src/ap/archipelago.cpp
src/ap/archipelago.h

also fixes a typo in `ScriptHost:AddOnLocationSectionChangedHandler` that would make LuaLS complain about correct use.
Example used for testing:
```lua
ScriptHost:AddWatchForCode("victory", "carltrons_robot", function(code)
local o = Tracker:FindObjectForCode(code)
---@cast o JsonItem
if o.Active then
local res = Archipelago:StatusUpdate(Archipelago.ClientStatus.GOAL)
if res then
print("Sent victory")
else
print("Error sending victory")
end
end
end)
```

Archipelago: Allow sending client status for manual (GOAL)

---

src/http/http.h
src/poptracker.cpp

Also adds a helper function to validate URLs.
This fixes showing a message box when dragging & droping garbage (only on Linux).

Ignore invalid URL for text drag&drop

---

src/core/statemanager.cpp
src/core/util.h
test/core/test_util.cpp

Also refactor and add tests.
Until we use wstring paths on windows, the utf8 paths would be invalid.

Ignore unicode for auto-save path and special symbols for default filename

---

src/core/version.cpp
src/core/version.h
test/core/test_version.cpp

also adds a test
Fixes problems where update notification did not work as expected.

Version Helper: correct comparison for semver and a.b.c.d notation

---

src/ui/settingswindow.cpp
src/ui/settingswindow.h
src/uilib/tooltip.cpp
src/uilib/tooltip.h
src/uilib/window.h

As reported here: https://discord.com/channels/937157230963339364/1277317101966856203
The tooltip in the settings window would show the item name instead of the stage name for progressive items with stage names.

Settings: show correct tooltip for progressive

---

src/packmanager/packmanager.cpp

This will allow updating a pack even after a bad update.

PackManager: Fall back to generic versions_url for invalid pack versions_url

---

src/poptracker.cpp

Adding enable_screensaver option to config, to allow computers to turn off the display/show a screensaver while poptracker is open. Default is true, can be changed to false in the config file to keep the screen awake as before.

Adding enable_screensaver

---

src/poptracker.cpp

Linter complains about this stuff depending on tab width because we don't force {}.

Fix indentation tabs->spaces

---

test/lib/test_lua.cpp

Also adds tests to
* not update Lua to 5.5 preview that would break a lot of packs
* verify Lua is configured to use C++ exceptions for errors to properly unwrap the stack

Update Lua to 5.4.7+2

---

src/packmanager/packmanager.cpp
test/core/test_version.cpp

Removes the work-around we had previously that could see a downgrade as upgrade.
\+ minor code reformatting

Use new version comparison to properly detect pack updates

---

src/uilib/ui.cpp

Also warn if a hotkey uses a modifier that is masked out.

UI: ignore scroll lock in hotkeys/keyboard handling

---

.gitignore
api/lua/definition/poptracker.lua
doc/PACKS.md
src/core/baseitem.h
src/core/jsonitem.cpp
src/core/jsonitem.h
src/core/jsonutil.h
src/core/luaitem.cpp
src/core/luaitem.h
src/core/tracker.cpp
src/core/tracker.h
src/ui/trackerview.cpp
src/uilib/colorhelper.h
test/core/test_jsonitem_provides.cpp
test/jsonutil/test_commasplit.cpp

Not all code comparisons were case-insensitive (CI). Also adds tests, primarily for CI.
Introduces an object cache that could change behaviour in some packs but shouldn't.
Replaces list<> by vector<> for code and adds an extra set that contains all lower case codes for faster checking.
Testing if vector<> for _ciAllCodes would be better was not done yet (TODO).
Allows to opt into deferred logic updates via
```lua
if Tracker.AllowDefferedLogicUpdate == false then
Tracker.AllowDefferedLogicUpdate = true
end
```
to run fewer logic updates (currently only uses when switching from bulk update back to normal update).

Make logic resolving 4x faster and allow CI codes for stages

---

src/poptracker.cpp

NOTE: this drops WinXP support
This is mainly for testing and currently needs to be set in `%appdata%\PopTracker\PopTracker.json` as `"ignore_hidpi": true` by hand.

Windows: Add option to ignore HIDPI and disable scaling

---

Makefile
linux/AppImageBuilder.yml
macosx/bundle_macosx_app.sh

* add schema to Windows dist zip - includes README.md since that is visible to the user
* add schema to the Ubuntu dist tar - includes README.md since that is visible to the user
* add schema and api to the AppImage/usr/share/poptracker/ - without README, since /usr/share is data files only
* add schema and api to the macos app bundle - without README, since Resources is data files only and not visible to the user

Build: include schema and api on all targets

---

.github/workflows/binaries.yaml
.github/workflows/test.yaml

The msys2 .a file for svt-av1 2.3.0 seems to be currently broken. This downgrades svt-av1 back to the previous version.
Long-term fix is probably to build libsdl2_image as part of make on Windows since the dependencies are crazy already.

CI: Downgrade svt-av1

---

src/core/autotracker.h
src/core/scripthost.cpp

https://discord.com/channels/937157230963339364/1171232344468901979/threads/1319421688064245851

Fix memory watches triggering when non-memory AT-backend connects

---

.github/workflows/binaries.yaml

Undo #194 which is not required anymore
Tested in CI

CI: undo svt1 fix

---

Makefile
src/app.rc
src/main.cpp
win32/exe.manifest.template.xml

Fixes https://discord.com/channels/937157230963339364/1323959597534285955
Msys2 added a default manifest resource that does not enable visual styles and that superseded our hack.
We now add our own resource that overrides the msys2 one, which also makes the hack obsolete.
Note: The internet claims that `RT_MANIFEST` should be 24, but when I tried `1 RT_MANIFEST ...` instead of `1 24 ...`, I ended up with a different entry in the .res.
We also set the windows version now to avoid some warnings; turns out we don't actually need to call into comdlg32, so neither neither `_WIN32_WINNT` nor `_WIN32_IE` is technically needed, but kept WINNT to get rid of the warnings.
(If we ever need to call stuff like InitCommonControlsEx, we should define WINNT to >=0x0600 and IE to >=0x0300)
We also now set …

Windows: add manifest file to re-enable visual styles

---

src/ui/maptooltip.cpp

They would strech to fit the container, putting overlay in the wrong spot.

Ui: fix overlay position of hosted items

---

src/ui/item.cpp

This restores the ability to abuse overlay_text in map locations and is probably more sane behavior in general.

UI: Remove special alignment handling when overlay text overflows

---

src/ui/trackerview.cpp
src/ui/trackerview.h

Improved performance when state can't be cached and multiple things change on a single frame.
Only enabled when AllowDeferredLogicUpdate is set, which will probably become the default in a future version.

Fix location performance under some circumstances

---

src/core/jsonitem.cpp
src/core/jsonitem.h
src/core/tracker.cpp
src/core/tracker.h
src/ui/trackerview.cpp

If order of definition was wrong, it would either not sync or endlessly update / crash.
This fixes the updating and also adds some safe guards to not end in the update loop.
Also prints the item name for the "click" debug message.

Fix problems with composite_toggle and toggle_badged

---

src/core/tracker.cpp

PopTracker would not notify the pack about changed codes, but cache logic results that are stale.
Test builds here: <https://github.com/black-sliver/PopTracker/actions/runs/13553712721>

Fix Lua logic staleness when loading state

---

src/core/jsonitem.cpp
src/core/jsonitem.h
src/ui/item.cpp
test/core/test_jsonitem_state.cpp

also adds tests to verify neither state (Active) nor stage (ActiveStage) becomes invalid for JsonItem during changeState
also adds an assert to getCurrentName to get a readable error should we ever reintroduce a wrong calculation
also adds an assert to Ui::Item to get a readable error should we ever apply an invalid state/stage to Ui::Item

Fix right click on progressive item with 0 stages

---

schema/packs/strict/items.json

codes directly on a progressive item do not work in other programs and also don't behave as one might expect when used as a hosted item

Remove codes from progressive/_toggle

---

.github/workflows/binaries.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml
BUILD.md
Makefile
macosx/build_thirdparty.sh
macosx/bundle_macosx_app.sh

also use more threads to speedup the build on intel runners.

macOS: update openssl to 3.0.16

---

.github/workflows/binaries.yaml
.github/workflows/scan-build.yaml
.github/workflows/test.yaml

* cancel previous runs of `scan-build` and `binaries` for the same PR since CI takes quite long now and the outdated results are typically useless
* don't fail fast for scan-build - let Windows finish if Linux failed in case they find different things
* skip the macos-13 default build, since the tested code paths are redundant

CI: better concurrency

---

Makefile

build: fix typo in Makefile

---

.gitmodules
Makefile
bench/core/bench_signal.cpp
bench/lib/bench_lua.cpp
bench/main.cpp

The ones added are only useful to compare compiler flags.
But we can use the framework for actual implementation benchmarks in the future as well.

Add some micro benchmarks

---

test/core/test_fs.cpp
test/core/test_pack.cpp

cmp was used to check if the function works and I forgot to remove it, resulting in an unused variable warning.
The second instance of it was a copy-pasta.

Test: fix unused variable warning in test_fs and test_pack

---

Makefile

this doubles Lua performance in release builds.

build: fix typo in LUA_C_FLAGS

---

Makefile

This improves performance for debug builds:
-fstack-protector-all has a real impact (over strong) if we don't inline all functions while not providing an actual security benefit.
This has almost no impact for relase builds:
strong may have been the default already (for most objs, on most systems)
This adds code that will crash the app before stack could overflow into heap.
Should not have a noticeable impact on performance as most function call will be unchanged by this.
I believe this should not really make any difference for the builds.

Better/safer CFLAGS

---

examples/read-settings-test/scripts/init.lua
src/core/pack.cpp
src/core/pack.h

When using user override for settings.json, the final version is merged from pack + override key by key. This was not the case when reading the file using io from Lua and it would instead ignore the override completely.

Lua: read the merged settings.json with io

---

api/lua/definition/poptracker.lua
doc/PACKS.md
schema/packs/settings.json
schema/packs/strict/settings.json
src/core/tracker.cpp
src/core/tracker.h
src/core/version.cpp
src/core/version.h
src/poptracker.cpp
test/core/test_version.cpp

* allows setting value from settings.json (can be overwritten from Lua)
* changes default for packs with 'ap' flag to true unless target version is < 0.31.0

Change Allow Deferred Logic Update default for ap and add to settings.json

---

Makefile
key/3B69F3B9A853297F.pub
key/F93AE9DB05595CD3.pub
linux/AppImageBuilder.yml
macosx/bundle_macosx_app.sh

F93AE9DB05595CD3 is the primary pub key file for minisign
3B69F3B9A853297F is a backup pub key file for minisign
i.e. use 
```bash
minisign -V -H -p key/F93AE9DB05595CD3.pub -m path/to/file
```
and if that says `Signature key id in path/to/file.minisig is 3B69F3B9A853297F`, use the other one.
The files contain a timestamp for when I want to rotate them. This is 1 year from now for the primary and 2 years from now for the backup key.

Add pub keys for minisign

---

.github/workflows/binaries.yaml
.github/workflows/release.yaml

Manually triggered "Build binaries" are test builds or RC builds for users. Users should be able to validate their origin before using them but also after the fact.
Release files are release files.

Use github attestation for manual Build Binaries and Release files

---

src/ap/aptracker.h

Also fixes Archipelago.CheckedLocations being out of sync.
Also minor cleanup.
Also fixes a potential crash (that was not possible to reach before).

Fix reset not checking checked locations for apmanual

---

src/ui/defaulttrackerwindow.cpp
src/ui/defaulttrackerwindow.h

This is technically a layout change, so merge for 0.32.0, not 0.31.x

Ui: set more reasonable min size for DefaultTrackerWindow

---

doc/PACKS.md
src/core/jsonitem.cpp
test/core/test_jsonitem_quantity.cpp

Also properly supports min_quantity < 0 now
and adds tests.

Consumable: limit AcquiredCount to min/max when set from Lua

---

src/core/tracker.cpp

We just spend a good 2 hours hunting down a typo in our init.lua script, these warnings would have helped a lot.
Maybe they can also help others.

Add warning when .json file could not be read

---

schema/packs/strict/locations.json

For some reason shape on the LocationSection was more lax in the strict schema (only checking for existence) so I made them at least match

Fix shape in strict locations schema

---

src/core/locationsection.cpp

Properties were changed to optional, but load code would misbehave in that case.

Fix LocationSection.load to work with new format

---

src/core/tracker.cpp
src/core/tracker.h

The old implementation could fail depending on calls made in Lua.
Also does some minor cleanup in header file.

Fix indirect connection detection for $-codes

---

community-packs.json

The previous pack was made by Coveleski and me.
We have since split and I have been ghosted. Coveleski has not been active in any AP server for ~6 months. I do not have control or even edit-access to the old repo. The old repo has several major logic issues that this fork fixes. This fork will also get new features as I am receiving support from GerbilJames and Alchav.
I have also made a PR to the AP-Repo to replace the link there: 
https://github.com/ArchipelagoMW/Archipelago/pull/5122
And will get the link in the pins of the Pokémon-RB channel changed.
Thanks for reading.

Update Pokémon RB Pack in community-packs.json

---

src/core/tracker.cpp

Reported here: <https://discord.com/channels/937157230963339364/1385453909933555764>
I believe the reason this wasn't found earlier is because the PopTracker-internal represantation when chaining rules is typically something like `{rule1},[rule2]` or `[rule1].{rule2}` rather than `{rule1,[rule2]}`.

Change order `[]` and `{}` is checked to allow `{...,[]}`

---

src/http/httpcache.cpp

added O_BINARY which enables binary caching under windows without corrupting the file with text-translation.
This can be used to cache images for example.

allow binary files for caching under windows
