Makefile

Quick fixes in Makefile for compatibility with Mac OS:
- command `lsb_release` does not exist on Mac. Had to move OS detection code earlier to only define DISTRO if os is LINUX.
- option `--ignore-fail-on-non-empty` does not exist for `rmdir` on Mac OS. Reworked `make clean` to account for that (best way I found to test if a directory is empty)...

Quick fixes in Makefile

---

macosx/build_thirdparty.sh

Added better error logging in `build_thirdparty.sh` script.

Better error logging

---

macosx/bundle_macosx_app.sh

This is a quickfix... not necessarily a fix for the macosx crash unfortunately :/

Macosx bundle quickfix

---

README.md
community-packs.json

Add The Messenger Track Pack to community_packs.json

---

doc/PACKS.md

Spelling error

---

src/core/tracker.cpp
src/core/tracker.h

Took code from Tracker::ProviderCountFor Code, and put it in new Tracker::RunLuaFunction methods for future reuse and extension.
Note that the functionality is now no longer specific to Tracker, and should eventually be put somewhere for global lua utilities

Extracted methods for calling Lua functions

---

src/core/tracker.cpp

also a bit of code cleanup/refactor

make glitched + inspect = unreachable, fix '@' in visibility

---

src/core/tracker.cpp

Moved handling of "Error running function" case from Tracker::runLuaFunction() to RunLuaFunction_inner(). This fixes a case where missing functions would hit both cases, and makes it easier to implement new calls to RunLuaFunction_inner() if needed

Fixed a bug where a missing Lua function would  hit 2 error cases

---

src/usb2snes/usb2snes.cpp

this may speed up shutdown by 1 interval

usb2snes: clear watches on shutdown

---

doc/PACKS.md
src/ui/trackerview.cpp
src/uilib/imagefilter.cpp
src/uilib/imagefilter.h

`"img_mods": "overlay|path/to/file|@disabled"`

allow image mods for overlay image mod

---

src/core/tracker.cpp
src/core/tracker.h
src/poptracker.cpp

this is mainly for pack authors, so they can check how far the pack is off or to suggest a new default limit

Add override_rule_exec_limit to config

---

src/ui/trackerview.cpp
src/ui/trackerview.h

skip updating untouched map locations
improving performance

Speedup rules for location updates

---

doc/PackCreation.md
doc/README.md

Sorry for the noise. I wanted to retain correct authors in the commits and rewriting your PR #93 failed hard :D

Add Pack creation guide

---

doc/AUTOTRACKING.md

The example Lua code was not valid

doc: typo in AUTOTRACKING.md

---

doc/AUTOTRACKING.md
doc/PACKS.md
src/core/autotracker.h
src/usb2snes/usb2snes.cpp
src/usb2snes/usb2snes.h

SNES: add sa-1 mapping support

---

src/uilib/ui.cpp

UI: increase scrolling distance/speed

---

src/core/jsonutil.h

this is used for codes and mods
Fixes https://discord.com/channels/937157230963339364/937163459534127174/1206320613090791514

Fix comma splitting with leading comma

---

doc/PACKS.md

Tiny one character PR. I'll add to it if I notice any others.

Fix spelling error in PACKS.md

---

.github/workflows/binaries.yaml
macosx/build_thirdparty.sh

also adds CI to check changed dependencies

macos: update dependencies

---

win32/cross-compile-libs-win32.sh

(those will be used for the next release build)

win32: update cross build dependencies

---

.github/workflows/binaries.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml
Makefile
test/README.md
test/core/test_locations_parser.cpp
test/jsonutil/test_commasplit.cpp

* jsonutil stringsplit
* location/section parser inheritance for empty child rules

Test: add unit testing and some tests

---

examples/rules_test/var_at/locations/locations.jsonc
src/core/tracker.cpp

Fix ':' breaking '@' and '^' rules

---

doc/PACKS.md
src/core/location.cpp
src/core/tracker.cpp
src/poptracker.cpp
src/poptracker.h

default DEBUG to false (=empty list) to disable FPS spam

Nicer console output, switch DEBUG to flags and init from config

---

examples/rules_test/manifest.json
examples/rules_test/var_scoutable_and_glitched/locations/locations.jsonc
src/core/tracker.cpp

Fix Sequence Break + Inspect access not showing up correctly

---

src/core/autotracker.h
src/usb2snes/usb2snes.cpp
src/usb2snes/usb2snes.h

So far I only found this one issue. Maybe we'd need to look for the rest in pack(s).

Autotracking: fix issues with SNES auto tracking

---

api/lua/definition/poptracker.lua
doc/PACKS.md
src/core/jsonitem.cpp
src/core/jsonitem.h
src/core/scripthost.cpp
src/core/tracker.cpp
src/core/tracker.h
src/ui/item.cpp
src/ui/item.h
src/ui/trackerview.cpp

also fixes a typo and slightly optimizes default disabled img mod.

Lua: JsonItem.Item behaves as override, implement JsonItem.IgnoreUserInput

---

README.md

I took the time to add this project as a package in nixpkgs, so I figured that some people would benefit from having it mentioned here.
We are currently one update behind on nixpkgs-unstable. I will see if I can find the time to update this at some point.

Mention Nix package in readme

---

doc/PackCreation.md
doc/README.md

I hope this is a sufficient enough sales pitch. 
otherwise i try to make i more detailed without going overboard but the detailed stuff is over in the scripts repo itself so i didnt want to double it up here

Add builder script sales pitch

---

schema/packs/strict/manifest.json

Add missing `apmanual` for `flag` enum

Fix manifest.json strict schema

---

community-packs.json

Icons are just some item images for now.

community-packs: Add all current Cyb3R packs to community-packs.json

---

src/ap/aptracker.h
src/core/autotracker.h
src/poptracker.cpp
src/ui/defaulttrackerwindow.cpp

Show name/alias in AP tooltip

---

community-packs.json

Add PopSnake pack to packlist

---

schema/packs/items.json
schema/packs/strict/items.json

and fix some typos and trailing whitespaces in items schema
resolves #190

fix composite_toggle schema

---

src/uilib/dlg.cpp

macos: translate .json and .zip to UTType identifier for tinyfd

---

src/core/tracker.cpp

https://discord.com/channels/937157230963339364/1171232344468901979/threads/1315449462352642079

Fix ref not working if they target sections with empty name

---

.github/workflows/test.yaml

Mirrors #203 for tests
(This would fail CI if wrong)

CI: undo svt1 fix in tests

---

.github/workflows/test.yaml
src/core/pack.cpp
test/core/test_pack.cpp

Fixes https://discord.com/channels/937157230963339364/1326272631330308191
And adds a test for it.

Windows: Fix crash when trying to install packs

---

src/ui/trackerwindow.cpp

The old code there seems to be obsolete now :-)

Fix window size not restoring when loading state

---

src/uilib/scrollvbox.h

Fixes https://discord.com/channels/937157230963339364/1323703686685528105

Fix map tooltip width containing invisible items

---

src/luasandbox/require.h

this fixes the require cache not working
fixes https://discord.com/channels/937157230963339364/1327014163284754525

Lua: make require return true for modules with no return

---

community-packs.json

Add Ape Escape to community packs

---

README.md

and some reformatting and cleanup.
Closes #223

Docs: add keyboard shortcuts to readme

---

src/ap/aptracker.h

We delay onClear to receiving the item sync reply. This should then have the same event timing as the original connect, allowing shenanigans like setting BulkUpdate mode.

AP: fix event timing for reset while connected

---

src/uilib/ui.cpp

A value in the struct changed, making a bug appear.

Fix crash with sdl2-compat

---

community-packs.json

- More manageable in a "versions" branch

Changed update path to Ape escape tracker

---

.github/workflows/binaries.yaml
.github/workflows/release.yaml
.github/workflows/scan-build.yaml
.github/workflows/test.yaml
.gitmodules
Makefile
src/uilib/dlg.cpp
test/README.md
test/main.cpp
test/mock/test_gmock_win32.cpp
test/uilib/test_dlg.cpp

also adds/enables gmock and gmock-win32
also adds 2 tests for the Windows implementation of Ui::Dlg using gmock-win32

Windows: fix unterminated string in Dlg::OpenFile and Dlg::SaveFile

---

src/core/sha256.cpp
test/core/test_sha256.cpp

Better SHA256_File error handling

---

doc/PACKS.md
schema/packs/strict/manifest.json
src/core/autotracker.h

add a ‘lua’ flag for the connector.lua

Add flag for Connector.lua (crowdcontrol) for any platform

---

src/uilib/colorhelper.h
src/uilib/imagefilter.cpp
test/uilib/test_imagefilter.cpp

* Fixes a nullptr deref
* Adds a bunch of asserts
* Adds some tests for ImageFilters (img_mods)

Fix crash with overlay img_mods with missing image

---

src/http/http.h

Increase receive buffer size
Also reorder members

HTTP: improve throughput

---

src/uilib/textutil.h
src/uilib/tooltip.cpp
src/uilib/tooltip.h
src/uilib/window.cpp
test/uilib/test_textutil.cpp

Ui: break long text in non-default-window tooltip

---

src/poptracker.cpp

Show messagebox
* if we can't delete the old backup
* if we can't move the current version to the backup location

Show info messages when there is a problem during pack update

---

src/ui/trackerview.cpp

Possible improvement for 0.31.0

Lazily update map tooltip on render if AllowDeferred

---

src/core/tracker.cpp
src/core/tracker.h
src/ui/trackerview.cpp

Possible improvement over #241 for 0.31.0

Defer section update events

---

src/poptracker.cpp

and add a PopTracker.json config option 'update_to_prerelease'.

Don't update to pre-releases by default

---

src/core/baseitem.h
src/core/util.h

* latest gnu toolchain complains about the missing stdint
* platforms where char is unsigned would fail the sanitize_dir test

Fix build on some platforms

---

src/core/util.h

Fixes a typo and some clang tidy warnings

Cleanup util.h

---

src/uilib/vbox.h

This is technically a bug fix, but could change layout, so merge for 0.32.0.

Ui: fix vertical array using the wrong margin for layout

---

doc/PACKS.md
schema/packs/locations.json
schema/packs/strict/locations.json
src/core/layoutnode.cpp
src/core/layoutnode.h
src/core/location.cpp
src/core/locationsection.cpp
src/core/locationsection.h
src/core/rule.h
src/ui/maptooltip.cpp
src/ui/trackerview.cpp

Also moves remaining LocationSection stuff out of location.cpp and minor cleanup of touched code.

Add item_size, width and height to LocationSection

---

community-packs.json

Added the Lunacid Tracker to the list https://github.com/ScorpioGameKing/Lunacid-Poptracker

Add Lunacid AP to community-packs.json

---

community-packs.json

Adding my Powerwash Simulator pack: https://github.com/skipperki1/manual_powerwashsimulator_hallojasper_PopTracker

Add Powerwash Simulator AP Manual to community-packs.json

---

.github/workflows/test.yaml
BUILD.md
shell.nix

Adeed shell.nix to load into a build enviorment including needed dependencies
Added Build instructions to Build.md

Add NixOS to build documentation and add nix-shell
